LANGUAGES = {
    "es": {
        "login_title": "Iniciar sesión",
        "register_title": "Registro",
        "username": "Usuario",
        "password": "Contraseña",
        "login_button": "Iniciar sesión",
        "register_button": "Registrarse",
        "forgot_password": "¿Olvidaste la contraseña?",
        "username_placeholder": "Ingrese su usuario, correo o teléfono",
        "password_placeholder": "Ingrese su contraseña",
        "google_login": "Iniciar sesión con Google",
        "help_button": "Ayuda",
        "credits_button": "Créditos",
        "error_facial":"Error en el login facial:{error}",



        # Ayuda
        "help_title": "Centro de Ayuda - Avatars vs Rooks",
        "help_section_login": "🔐 Inicio de sesión",
        "help_section_login_text": "Si ya tienes una cuenta, ingresa tu información en los espacios señalados.\nDebes ingresar tu usuario, correo o teléfono y tu contraseña.\nSi tus datos son correctos, podrás acceder al sistema.",
        "help_section_register": "🆕 Registro de usuario",
        "help_section_register_text": "Si eres un nuevo jugador, selecciona 'Registrarse'.\nCompleta los campos solicitados con tus datos.\nLuego de registrarse correctamente volverás a la página de Inicio de Sesión.",
        "help_section_forgot": "❓ Recuperar contraseña",
        "help_section_forgot_text": "Si olvidaste tu contraseña, haz clic en '¿Olvidaste la contraseña?'.\nSe te guiará por un proceso para restablecerla y recuperar el acceso.",
        "help_back": "Volver",

        # Créditos
        "credits_title": "Equipo de Desarrollo - Avatars vs Rooks",
        "credits_leader": "Líder Técnico\nDesarrollador",
        "credits_member": "Miembro",
        "credits_admin": "Administrador de Infraestructura\nDesarrollador",
        "credits_ux": "Diseñador de experiencia de Usuario\nDesarrollador",
        "credits_tester": "Líder de Pruebas\nDesarrollador",
        "credits_back": "Volver",

        # Verificación de datos (login)
        "user_error": "Error, por favor ingrese su usuario",
        "password_error": "Error Por favor ingresa tu contraseña",
        "user_ver": "Próximamente, aquí se abrirá el menú principal del juego",
        "error_uc": "Error, usuario o contraseña incorrectos",
        "error_credentials": "Error al verificar credenciales:",

        #Recuperacion de Contraseña
        "error_facial":"Error en el login facial:{error}",
        "photo_perfil":"Seleccionar foto de perfil",
        "succes_photo":"Éxito, foto de perfil cargada correctamente",
        "error_photo":"Error, no se pudo cargar la imagen: {error}",
        "recover_password":"Recuperar contraseña",
        "enter_username":"Ingresa tu nombre de usuario:",
        "error_usernot_found":"Error, usuario no encontrado",
        "error_usernot_question":"Error, usuario no tiene pregunta de seguridad configurada",
        "error_recovery_question":"Error, al recuperar la pregunta de seguridad",
        "continue":"Continuar",
        "return_login":"← Volver al login",
        "question_security":"Pregunta de Seguridad",
        "answer":"Tu respuesta:",
        "enter_answer":"Error, ingresa tu respuesta",
        "answer_incorrect":"Error respuesta incorrecta",
        "verify":"VERIFICAR",
        "cancel":"Cancelar",
        "reset_password":"Restablecer contraseña",
        "new_password":"Nueva contraseña:",
        "confirm_password":"Confirmar contraseña:",
        "error_enter_all":"Error, por favor ingresa todos los campos",
        "paswords_notmatch":"Error, las contraseñas no coinciden",
        "min_caracters":"Error, la contraseña debe tener al menos 4 caracteres",
        "successful_change":"Éxito, contraseña restablecida correctamente.\n¡Ahora puedes iniciar sesión!",
        "error_change":"Error, al restablecer contraseña",
        "restore":"RESTABLECER",

        #Registro
        "personal_information":"Información personal",
        "username2":"Nombre+:",
        "username3":"Ingrese su nombre",
        "lats_name":"Apellidos +",
        "insert_sumernames":"Ingrese sus apellidos",
        "answer_security":"Respuesta de Seguridad:",
        "add_photo":"+\nAgregar foto",
        "date_birthday":"Fecha de nacimiento +:",
        "nationality":"Nacionalidad +:",
        "selec_nationality":"Selecciona tu nacionalidad",
        "account_security":"Cuenta y Seguridad",
        "insert_username":"Ingrese su usuario",
        "restriccion1":"❌ Entre 4 y 256 caracteres",
        "restriccion2":"❌ Solo letras y números (sin espacios ni caracteres especiales)",
        "email":"Correo electrónico:",
        "insert_email":"Ingrese su correo electrónico",
        "restriccion3":"Entre 8 y 23 caracteres",
        "restriccion4":" Solo letras y números",
        "restriccion5":"  Sin espacios ni caracteres especiales",
        "facial_identification":"Reconocimiento facial (Opcional)",
        "enable_facial":"Habilitar",
        "capture_face":"Capturar rostro",
        "pay_information":"Información de pago (opcional)",
        "card_number":"Numero de tarjeta",
        "expiry_date":"Fecha de expiración",
        "name_holder":"Nombre del titular",
        "error_register_facial": "Error al registrar rostro: {error}",

        #Guardar datos registro
        "error_restr_password":"Error, las contraseñas no cumplen con los requerimientos",
        "error_name":"Error, por favor ingresa tu nombre",
        "error_sumername":"Error, por favor ingresa tus apellidos",
        "error_questionsecury":"Error, debes responder la pregunta de seguridad",
        "enter_nationality": "Ingrese su nacionalidad",
        "error_nationality": "Error, por favor ingresa tu nacionalidad",
        "error_email": "Error, por favor ingresa tu correo electrónico",
        "error_email2": "Error, por favor ingresa un correo electrónico válido",
        "error_password3":"Error, por favor ingresa una contraseña",
        "user_exist":"Error, el usuario ya existe",

        #Preguntas
        "error_guardar_pregunta":"Error, al guardar la pregunta: {message}",
        "register_succselfol":"Éxito ¡Registro exitoso!",
        "error_register_usuario":"Error, al registrar usuario: {e}",
        "pasword_invalid":"Contraseña inválida",
        "condicion_pasword":"La contraseña debe tener entre 8 y 23 caracteres alfanuméricos.",
        "condicion_pasword2":"La contraseña solo puede contener letras y números\n(sin caracteres especiales ni espacios).",
        "user_invalid":"Usuario inválido",
        "condicion_user1":"El nombre de usuario debe tener entre 4 y 256 caracteres alfanuméricos.",
        "condicion_user2":"El nombre de usuario solo puede contener letras y números\n(sin caracteres especiales ni espacios).",
        "user_ind":"Usuario no disponible",
        "user_ocupado":"Este nombre de usuario ya está en uso.\n\nPor favor, elige otro.",
        "pregunta1":"¿Cuál es el nombre de tu primera mascota?",
        "pregunta2":"¿Cuál es el nombre de tu mejor amigo de la infancia?",
        "pregunta3":"¿En qué año conociste a tu mejor amigo?",
        "pregunta4":"¿Cuál fue tu primer trabajo?",




    },

    "en": {
        "login_title": "Login",
        "register_title": "Register",
        "username": "Username",
        "password": "Password",
        "login_button": "Login",
        "register_button": "Register",
        "forgot_password": "Forgot password?",
        "username_placeholder": "Enter your username, email or phone",
        "password_placeholder": "Enter your password",
        "google_login": "Sign in with Google",
        "help_button": "Help",
        "credits_button": "Credits",

        # Help
        "help_title": "Help Center - Avatars vs Rooks",
        "help_section_login": "🔐 Login",
        "help_section_login_text": "If you already have an account, enter your information in the indicated fields.\nYou must enter your username, email or phone and your password.\nIf your data is correct, you will be able to access the system.",
        "help_section_register": "🆕 User Registration",
        "help_section_register_text": "If you are a new player, select 'Register'.\nFill in the requested fields with your data.\nAfter registering successfully, you will return to the Login page.",
        "help_section_forgot": "❓ Recover password",
        "help_section_forgot_text": "If you forgot your password, click on 'Forgot password?'.\nYou will be guided through a process to reset it and regain access.",
        "help_back": "Back",

        # Credits
        "credits_title": "Development Team - Avatars vs Rooks",
        "credits_leader": "Technical Leader\nDeveloper",
        "credits_member": "Member",
        "credits_admin": "Infrastructure Administrator\nDeveloper",
        "credits_ux": "User Experience Designer\nDeveloper",
        "credits_tester": "Testing Leader\nDeveloper",
        "credits_back": "Back",

        # Recuperar Contraseña
        "user_error": "Error, please enter your username",
        "password_error": "Error Please enter your password",
        "user_ver": "Coming soon, the game's main menu will open here",
        "error_uc": "Error, incorrect username or password",
        "error_credentials": "Error verifying credentials:",
        "error_facial":"Facial login error:{error}",
        "photo_perfil":"Select profile picture",
        "succes_photo":"Success, profile picture uploaded successfully",
        "error_photo":"Error, could not load image: {error}",
        "recover_password":"Recover password",
        "enter_username":"Enter your username:",
        "error_usernot_found":"Error, user not found",
        "error_usernot_question":"Error, user does not have a security question set",
        "error_recovery_question":"Error, retrieving security question",
        "continue":"Continue",
        "return_login":"← Return to login",
        "question_security":"Security Question",
        "answer":"Your answer:",
        "enter_answer":"Error, please enter your answer",
        "answer_incorrect":"Error incorrect answer",
        "verify":"VERIFY",
        "cancel":"Cancel",
        "reset_password":"Reset password",
        "new_password":"New password:",
        "confirm_password":"Confirm password:",
        "error_enter_all":"Error, please enter all fields",
        "paswords_notmatch":"Error, passwords do not match",
        "min_caracters":"Error, password must be at least 4 characters",
        "successful_change":"Success, password reset successfully.\nYou can now log in!",
        "error_change":"Error, resetting password",
        "restore":"RESTORE",

        #Registro
        "personal_information":"Personal Information",
        "username2":"Name+:",
        "username3":"Enter your name",
        "lats_name":"Surnames +",
        "insert_sumernames":"Insert your surnames",
        "answer_security":"Answer of security:",
        "add_photo":"+\nAdd photo:",
        "date_birthday":"Date of birth+ :",
        "nationality":"Nationality +:",
        "selec_nationality":"Select your nationality:",
        "account_security":"Account and Security",
        "insert_username":"Enter your username",
        "restriccion1":"❌ Between 4 and 256 characters",
        "restriccion2":"❌ Only letters and numbers (no spaces or special characters)",
        "email":"Mail:",
        "insert_email":"Enter your email",
        "restriccion3":"Between 8 and 23 characters",
        "restriccion4":" Only letters and numbers",
        "restriccion5":" ❌ No spaces or special characters",
        "facial_identification":"Facial recognition (Optional)",
        "enable_facial":"Enable",
        "capture_face":"Capture face",
        "pay_information":"Payment information (optional)",
        "card_number":"Card number",
        "expiry_date":"Expiry date",
        "name_holder":"Name of the holder",
        "error_register_facial": "Error when registering face: {error}",

        #Guardar datos registro
        "error_restr_password":"Error, passwords do not meet requirements",
        "error_name":"Error, please enter your name",
        "error_sumername":"Error, please enter your surnames",
        "error_questionsecury":"Error, you must answer the security question",
        "enter_nationality": "Enter your nationality",
        "error_nationality": "Error, please enter your nationality",
        "error_email": "Error, please enter your email address",
        "error_email2": "Error, please enter a valid email address",
        "error_password3":"Error, please enter a password",
        "user_exist":"Error, user already exists",

        #Preguntas
        "error_guardar_pregunta":"Error, saving question: {message}",
        "register_succselfol":"Success Registration successful!",
        "error_register_usuario":"Error, registering user: {e}",
        "pasword_invalid":"Invalid password",
        "condicion_pasword":"The password must be between 8 and 23 alphanumeric characters.",
        "condicion_pasword2":"The password can only contain letters and numbers\n(no special characters or spaces).",
        "user_invalid":"Invalid user",
        "condicion_user1":"The username must be between 4 and 256 alphanumeric characters.",
        "condicion_user2":"The username can only contain letters and numbers\n(no special characters or spaces).",
        "user_ind":"Username not available",
        "user_ocupado":"This username is already in use.\n\nPlease choose another one.",
        "pregunta1":"What is the name of your first pet?",
        "pregunta2":"What is the name of your best childhood friend?",
        "pregunta3":"What year did you meet your best friend?",
        "pregunta4":"What was your first job?",

    },

    "hu": {
        "login_title": "Bejelentkezés",
        "register_title": "Regisztráció",
        "username": "Felhasználónév",
        "password": "Jelszó",
        "login_button": "Bejelentkezés",
        "register_button": "Regisztráció",
        "forgot_password": "Elfelejtette a jelszavát?",
        "username_placeholder": "Adja meg felhasználónevét, e-mailjét vagy telefonszámát",
        "password_placeholder": "Adja meg jelszavát",
        "google_login": "Bejelentkezés Google-lal",
        "help_button": "Súgó",
        "credits_button": "Kreditek",

        # Súgó
        "help_title": "Súgóközpont - Avatars vs Rooks",
        "help_section_login": "🔐 Bejelentkezés",
        "help_section_login_text": "Ha már van fiókja, adja meg adatait a megadott mezőkben.\nAdja meg felhasználónevét, e-mail címét vagy telefonszámát és jelszavát.\nHa az adatok helyesek, hozzáférhet a rendszerhez.",
        "help_section_register": "🆕 Felhasználó regisztráció",
        "help_section_register_text": "Ha új játékos, válassza a 'Regisztráció' lehetőséget.\nTöltse ki a kért mezőket adataival.\nA sikeres regisztráció után visszatér a Bejelentkezés oldalra.",
        "help_section_forgot": "❓ Jelszó visszaállítása",
        "help_section_forgot_text": "Ha elfelejtette jelszavát, kattintson az 'Elfelejtette a jelszavát?' gombra.\nEgy folyamaton keresztül visszaállíthatja azt és visszanyerheti a hozzáférést.",
        "help_back": "Vissza",

        # Kredit
        "credits_title": "Fejlesztői csapat - Avatars vs Rooks",
        "credits_leader": "Technikai vezető\nFejlesztő",
        "credits_member": "Tag",
        "credits_admin": "Infrastruktúra adminisztrátor\nFejlesztő",
        "credits_ux": "Felhasználói élmény tervező\nFejlesztő",
        "credits_tester": "Tesztelési vezető\nFejlesztő",
        "credits_back": "Vissza",

        # Adatellenőrzés (login)
        "user_error": "Hiba, kérjük, adja meg felhasználónevét",
        "password_error": "Hiba, kérjük, adja meg jelszavát",
        "user_ver": "Hamarosan itt nyílik meg a játék főmenüje",
        "error_uc": "Hiba, helytelen felhasználónév vagy jelszó.",
        "error_credentials": "Hiba a hitelesítő adatok ellenőrzése során:",
        "error_facial":"Hiba az arc bejelentkezéskor:{error}",
        "photo_perfil":"Profilkép kiválasztása",
        "succes_photo":"Siker, profilkép sikeresen feltöltve",
        "error_photo":"Hiba, nem sikerült betölteni a képet: {error}",
        "recover_password":"Jelszó visszaállítása",
        "enter_username":"Adja meg felhasználónevét:",
        "error_usernot_found":"Hiba, felhasználó nem található",
        "error_usernot_question":"Hiba, a felhasználónak nincs biztonsági kérdése beállítva",
        "error_recovery_question":"Hiba a biztonsági kérdés lekérése során",
        "continue":"Folytatás",
        "return_login":"← Vissza a bejelentkezéshez",
        "question_security":"Biztonsági kérdés",
        "answer":"A válasza:",
        "enter_answer":"Hiba, kérjük, adja meg válaszát",
        "answer_incorrect":"Hiba, helytelen válasz",
        "verify":"ELLENŐRZÉS",
        "cancel":"Mégse",
        "reset_password":"Jelszó visszaállítása",
        "new_password":"Új jelszó:",
        "confirm_password":"Jelszó megerősítése:",
        "error_enter_all":"Hiba, kérjük, töltse ki az összes mezőt",
        "paswords_notmatch":"Hiba, a jelszavak nem egyeznek meg",
        "min_caracters":"Hiba, a jelszónak legalább 4 karakterből kell állnia",
        "successful_change":"Siker, a jelszó sikeresen visszaállítva.\nMost már bejelentkezhet!",
        "error_change":"Hiba a jelszó visszaállításakor",
        "restore":"VISSZAÁLLÍTÁS",

        #Registro
        "personal_information":"Személyes adatok",
        "username2":"Név+:",
        "username3":"Írja be a nevét",
        "lats_name":"Vezetéknevek+",
        "insert_sumernames":"Írja be vezetéknevét",
        "answer_security":"Biztonsági válasz:",
        "add_photo":"+\nFotó hozzáadása:",
        "date_birthday":"Születési dátum +:",
        "nationality":"Nemzetiség +:",
        "selec_nationality":"Válassza ki nemzetiségét:",
        "account_security":"Fiók és biztonság",
        "insert_username":"Adja meg felhasználónevét",
        "restriccion1":"❌ 4 és 256 karakter között",
        "restriccion2":"❌ Csak betűk és számok (nincs szóköz vagy speciális karakter)",
        "email":"Felad:",
        "insert_email":"Adja meg e-mail címét:",
        "restriccion3":"8 és 23 karakter között",
        "restriccion4":" Csak betűk és számok",
        "restriccion5":" ❌ Nincs szóköz vagy speciális karakter",
        "facial_identification":"Arcfelismerés (opcionális)",
        "enable_facial":"Engedélyezés",
        "capture_face":"Arc rögzítése",
        "pay_information":"Fizetési információ (opcionális)",
        "card_number":"Kártyaszám",
        "expiry_date":"Lejárati dátum",
        "name_holder":"A tulajdonos neve",
        "error_register_facial": "Hiba az arc regisztrálásakor: {error}",

        #Guardar datos registro
        "error_restr_password":"Hiba, a jelszavak nem felelnek meg a követelményeknek",
        "error_name":"Hiba, kérjük, adja meg nevét",
        "error_sumername":"Hiba, kérjük, adja meg vezetéknevét",
        "error_questionsecury":"Hiba, válaszolnia kell a biztonsági kérdésre",
        "enter_nationality":"Kérjük, adja meg a nemzetiségét:",
        "error_nationality":"Hiba, kérjük, adja meg nemzetiségét",
        "error_email": "Hiba, kérjük, adja meg e-mail címét",
        "error_email2": "Hiba, kérjük, adjon meg egy érvényes e-mail címet",
        "error_password3": "Hiba, kérjük, adja meg a jelszavát",
        "user_exist":"Hiba, a felhasználó már létezik",

        #Preguntas
        "error_guardar_pregunta":"Hiba, kérdés mentése: {message}",
        "register_succselfol":"Sikeres regisztráció!",
        "error_register_usuario":"Hiba a felhasználó regisztrálásakor: {e}",
        "pasword_invalid":"Érvénytelen jelszó",
        "condicion_pasword":"A jelszónak 8 és 23 alfanumerikus karakter között kell lennie.",
        "condicion_pasword2":"A jelszó csak betűket és számokat tartalmazhat\n(nincs speciális karakter vagy szóköz).",
        "user_invalid":"Érvénytelen felhasználó",
        "condicion_user1":"A felhasználónévnek 4 és 256 alfanumerikus karakter között kell lennie.",
        "condicion_user2":"A felhasználónév csak betűket és számokat tartalmazhat\n(nincs speciális karakter vagy szóköz).",
        "user_ind":"A felhasználónév nem elérhető",
        "user_ocupado":"Ez a felhasználónév már használatban van.\n\nKérjük, válasszon egy másikat.",
        "pregunta1":"Mi volt az első háziállatod neve?",
        "pregunta2":"Mi volt a legjobb gyerekkori barátod neve?",
        "pregunta3":"Melyik évben ismerkedtél meg a legjobb barátoddal?",
        "pregunta4":"Mi volt az első munkád?",



    }
}

current_language = "es"

def set_language(lang_code):
    global current_language
    if lang_code in LANGUAGES:
        current_language = lang_code

def t(key):
    return LANGUAGES[current_language].get(key, key)